version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
      timezone: Asia/Seoul
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
      timezone: Asia/Seoul
