name: Release
on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: chussum/fortivpn-proxy

    steps:
      - uses: actions/checkout@v3.5.0

      - uses: docker/setup-buildx-action@v2.8.0

      - name: Build and push
        env:
          REGISTRY: ghcr.io
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login "$REGISTRY" -u "$USERNAME" --password-stdin <<< "$PASSWORD"
          docker buildx build --platform=linux/amd64,linux/arm/v7,linux/arm64/v8 --push -t "$REGISTRY/$IMAGE_NAME:${{ github.ref_name }}" .
          rm -rf ~/.docker
